spring:
  application:
    name: vacation

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?TimeZone=UTC
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

      jackson:
        time-zone: UTC

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/changelog-master.yaml

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

jwt:
  secret: fX9pL2mK8nQ4rT7vY1wZ3uA6bC0dE5gH8iJ2kM4nO6pQ9rS1tU3vW5xY7zA9bC2eF4gH6iJ8kL0mN2oP4qR6sT8uV0wX2yZ4aB6cD8eF0gH2iJ4kL6mN8oP0qR2sT4u
  expiration: 180000
  refresh-expiration: 300000